# Generated by Django 4.2.7 on 2024-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
